# https://aka.ms/yaml


jobs:

- job: 'Build_Windows'
  timeoutInMinutes: 780
  cancelTimeoutInMinutes: 1

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - script: 'mkdir C:\workdir_tmp\'
  - script: $(Build.SourcesDirectory)/install-script-win.cmd
    displayName: 'Windows GRPC'
    workingDirectory: 'C:\workdir_tmp\'

  - task: PublishPipelineArtifact@1
    inputs:
      path: 'C:\workdir_tmp\output_dir'
      artifact: grpc_deps_windows
