# https://aka.ms/yaml


jobs:

- job: 'Build_macOS'
  pool:
    vmImage: 'macos-10.13'
  steps:
    - script: git submodule update --init --recursive
      displayName: 'Checkout Submodules'

    - script: ./install-script-osx.sh
      displayName: 'Setup build'

    - task: PublishPipelineArtifact@1
      inputs:
        path: 'output/'
        artifact: obs_deps_macos
