# https://aka.ms/yaml


jobs:

- job: 'Build_Windows'
  pool:
    vmImage: 'windows-2019'
  steps:

  - script: ./install-script-win.cmd
    displayName: 'Download / Setup Deps / Run CMake'

  - task: MSBuild@1
    displayName: 'Build 64-bit'
    inputs:
      msbuildArguments: '/m /p:Configuration=RelWithDebInfo'
      solution: .\obs_src\build_64\obs-studio.sln

  - task: MSBuild@1
    displayName: 'Build 32-bit'
    inputs:
      msbuildArguments: '/m /p:Configuration=RelWithDebInfo'
      solution: .\obs_src\build_32\obs-studio.sln

#  - script: ./post-install-script-win.cmd
#    displayName: ''

  - task: PublishPipelineArtifact@1
    inputs:
      path: './'
      artifact: obs_deps_windows
