# https://aka.ms/yaml


jobs:

- job: 'Build_macOS'
  timeoutInMinutes: 780
  cancelTimeoutInMinutes: 1
  pool:
    vmImage: 'macos-10.13'
  steps:
    - script: ./install-script-osx.sh --install-deps
      displayName: 'create grpc deps'

    - task: PublishPipelineArtifact@1
      inputs:
        path: 'vcpkg/output/'
        artifact: grpc_deps_macos
