# https://aka.ms/yaml


jobs:

- job: 'Build_Windows'
  pool:
    vmImage: 'windows-2019'

  steps:
    - script: ./install-script-win.cmd
      displayName: 'run'
      workingDirectory: $(Build.SourcesDirectory)

    - task: PublishPipelineArtifact@1
      inputs:
        path: $(Build.SourcesDirectory)/build/
        artifact: out

    - script: exit 1
