# https://aka.ms/yaml


jobs:

- job: 'Build_Windows'
  pool:
    vmImage: 'windows-2019'
  steps:

  - script: ./install-script-win.cmd
    displayName: 'Build OBSs'
    workingDirectory: $(Build.SourcesDirectory)
    env:
      PRUNE_BUILDS: "YES"

  - task: PublishPipelineArtifact@1
    inputs:
      path: $(Build.SourcesDirectory)
      artifact: obs_deps_windows
