# https://aka.ms/yaml

variables:
  VC_COMMIT: "9b72cad7f0c7c3bc364cb471bf624e6cae3e1aef" #grpc 1.33.1, protobuf 3.14.0
  VC_RELEASE_ONLY: YES
  GOOGLE_APIS_COMMIT: "959b0bcea3f542b8d6964c910b11fb847b12a5ad"

jobs:

  - job: 'GRPC_x64_windows_static'
    timeoutInMinutes: 780
    cancelTimeoutInMinutes: 1

    pool:
      vmImage: 'windows-2019'
    steps:
      - script: 'mkdir C:\workdir_tmp\'

      - script: $(Build.SourcesDirectory)/install-script-win.cmd
        displayName: 'Windows GRPC'
        workingDirectory: 'C:\workdir_tmp\'
        env:
          VC_INSTALL_PKG: "grpc:x64-windows-static"
          VC_COMMIT: $(VC_COMMIT)
          VC_RELEASE_ONLY: $(VC_RELEASE_ONLY)
          GOOGLE_APIS_COMMIT: $(GOOGLE_APIS_COMMIT)

      - task: PublishPipelineArtifact@1
        inputs:
          path: 'C:\workdir_tmp\output_dir'
          artifact: grpc_deps_windows_x64_static

  - job: 'GRPC_x86_windows_static'
    timeoutInMinutes: 780
    cancelTimeoutInMinutes: 1

    pool:
      vmImage: 'windows-2019'
    steps:
      - script: 'mkdir C:\workdir_tmp\'

      - script: $(Build.SourcesDirectory)/install-script-win.cmd
        displayName: 'Windows GRPC'
        workingDirectory: 'C:\workdir_tmp\'
        env:
          VC_INSTALL_PKG: "grpc:x86-windows-static"
          VC_COMMIT: $(VC_COMMIT)
          VC_RELEASE_ONLY: $(VC_RELEASE_ONLY)
          GOOGLE_APIS_COMMIT: $(GOOGLE_APIS_COMMIT)

      - task: PublishPipelineArtifact@1
        inputs:
          path: 'C:\workdir_tmp\output_dir'
          artifact: grpc_deps_windows_x86_static

  - job: 'GRPC_x64_windows'
    timeoutInMinutes: 780
    cancelTimeoutInMinutes: 1

    pool:
      vmImage: 'windows-2019'
    steps:
      - script: 'mkdir C:\workdir_tmp\'

      - script: $(Build.SourcesDirectory)/install-script-win.cmd
        displayName: 'Windows GRPC'
        workingDirectory: 'C:\workdir_tmp\'
        env:
          VC_INSTALL_PKG: "grpc:x64-windows"
          VC_COMMIT: $(VC_COMMIT)
          VC_RELEASE_ONLY: $(VC_RELEASE_ONLY)
          GOOGLE_APIS_COMMIT: $(GOOGLE_APIS_COMMIT)

      - task: PublishPipelineArtifact@1
        inputs:
          path: 'C:\workdir_tmp\output_dir'
          artifact: grpc_deps_windows_x64

  - job: 'GRPC_x86_windows'
    timeoutInMinutes: 780
    cancelTimeoutInMinutes: 1

    pool:
      vmImage: 'windows-2019'
    steps:
      - script: 'mkdir C:\workdir_tmp\'

      - script: $(Build.SourcesDirectory)/install-script-win.cmd
        displayName: 'Windows GRPC'
        workingDirectory: 'C:\workdir_tmp\'
        env:
          VC_INSTALL_PKG: "grpc:x86-windows"
          VC_COMMIT: $(VC_COMMIT)
          VC_RELEASE_ONLY: $(VC_RELEASE_ONLY)
          GOOGLE_APIS_COMMIT: $(GOOGLE_APIS_COMMIT)

      - task: PublishPipelineArtifact@1
        inputs:
          path: 'C:\workdir_tmp\output_dir'
          artifact: grpc_deps_windows_x86
