# https://aka.ms/yaml


jobs:
- job: 'Build_Windows'
  pool:
    vmImage: 'vs2017-win2016'
  steps:

  - script: ./install-script-win.cmd
    displayName: 'Download / Setup Deps / Run CMake'

  - task: MSBuild@1
    displayName: 'Build 64-bit'
    inputs:
      msbuildArguments: '/m /p:Configuration=RelWithDebInfo'
      solution: .\obs_src\build_64\obs-studio.sln

  - task: MSBuild@1
    displayName: 'Build 32-bit'
    inputs:
      msbuildArguments: '/m /p:Configuration=RelWithDebInfo'
      solution: .\obs_src\build_32\obs-studio.sln

  - script: ./post-install-script-win.cmd
    displayName: 'Pack archive'

#  - task: PublishBuildArtifacts@1
#    inputs:
#      pathtoPublish: './archive.7z'
#      artifactName: obs_deps
#      parallel: true
#      parallelCount: 8

  - task: PublishPipelineArtifact@1
    inputs:
      path: './archive.7z'
      artifact: obs_deps

