# https://aka.ms/yaml


jobs:

- job: 'Build_Linux'

  pool:
    vmImage: 'ubuntu-18.04'

  steps:
    - script: ./install-script-linux.sh
      displayName: 'Setup & Build'

    - task: PublishPipelineArtifact@1
      inputs:
        path: 'output/'
        artifact: obs_deps_linux
